// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gretter.proto

package com.ytking.proto.greeter;

public final class Gretter {
  private Gretter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ytking_proto_greeter_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ytking_proto_greeter_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ytking_proto_greeter_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ytking_proto_greeter_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgretter.proto\022\030com.ytking.proto.greete" +
      "r\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHello" +
      "Reply\022\017\n\007message\030\001 \001(\t2e\n\007Greeter\022Z\n\010Say" +
      "Hello\022&.com.ytking.proto.greeter.HelloRe" +
      "quest\032$.com.ytking.proto.greeter.HelloRe" +
      "ply\"\000B\034\n\030com.ytking.proto.greeterP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ytking_proto_greeter_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ytking_proto_greeter_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ytking_proto_greeter_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_ytking_proto_greeter_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ytking_proto_greeter_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ytking_proto_greeter_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
